DROP ROLE IF EXISTS auth;
CREATE ROLE auth WITH
SUPERUSER LOGIN
UNENCRYPTED PASSWORD '1234';

DROP DATABASE IF EXISTS auth_inmemory_example;
CREATE DATABASE auth_inmemory_example
ENCODING = 'UTF8'
OWNER = auth;